version: '3'
services:
  flask:
    build: .
    command: python3 app/app.py
    ports:
      - "5001:5001"

  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/var/www/html
    restart: always
    depends_on:
      - flask
    networks:
      - default
      - common

networks:
  common:
    external: true